### ISSUE TITLE
Works, but only on one set of lines at a time.

### ISSUE THREAD

**Issue by SergeantFTC** [devpack/vmware-synaptics-touchpad-scroll#2]
Host: Windows 8.1 64-bit
VM Technology: VMWare player 6.0.1 build-1379776
Guest: Kali Linux 64-bit.
TouchPad Driver: Dell Touchpad Driver 17.0.8
Option 0 used to launch the latest release version of vmware_scroll_start.exe

Scrolling upward with 2 fingers on my trackpad causes the display to move up a certain number of lines, as expected. However, continuing to move my fingers upwards does nothing. To move up further, I have to lift my fingers and start again. At that point it's faster just to grab the scroll bar.

**Comment by devpack** [comment]
I had a similar issue before fixing my registry, did follow http://blog.alexou.net/2010/07/scrolling-in-gtk-apps-with-synaptics-driver ? However I only tested Windows 7 64bit so far.

**Comment by SergeantFTC** [comment]
No actually, I didn't. I opened Wireshark to see if I was having the original issue or not, and I wasn't, so I didn't worry about it. Will try it and report back.

**Comment by SergeantFTC** [comment]
Worked great, thanks! Scrolling looks a bit cleaner that way too. :)
